package org.cryptomator.jose.alg;

import com.google.gson.JsonObject;
import org.cryptomator.jose.JoseDecryptException;
import org.cryptomator.jose.util.Curve;
import org.cryptomator.jose.util.Destroyables;
import org.cryptomator.jose.util.ECHelper;

import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.KeyAgreement;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import java.math.BigInteger;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.security.InvalidKeyException;
import java.security.KeyFactory;
import java.security.NoSuchAlgorithmException;
import java.security.interfaces.ECPrivateKey;
import java.security.interfaces.ECPublicKey;
import java.security.spec.ECPoint;
import java.security.spec.ECPublicKeySpec;
import java.security.spec.InvalidKeySpecException;
import java.util.Arrays;
import java.util.Base64;

public final class EcdhEsAlg extends AbstractAlg {

	private static final String EC_ALG = "EC";

	public enum Type {
		ECDH_ES_A256KW("ECDH-ES+A256KW", "AESWrap", "AES",32),
		;

		private final String jwaAlgName;
		private final String jcaKwAlgName;
		private final String jcaKeyAlgName;
		private final int keyLength;

		Type(String jwaAlgName, String jcaKwAlgName, String jcaKeyAlgName, int keyLength) {
			this.jwaAlgName = jwaAlgName;
			this.jcaKwAlgName = jcaKwAlgName;
			this.jcaKeyAlgName = jcaKeyAlgName;
			this.keyLength = keyLength;
		}
	}

	private final Type type;
	private final Curve curve;
	private final ECPublicKey publicKey;
	private final ECPrivateKey privateKey;

	public EcdhEsAlg(Type type, Curve curve, ECPublicKey publicKey, ECPrivateKey privateKey) {
		this.type = type;
		this.curve = curve;
		this.publicKey = publicKey == null ? null : ECHelper.validateKey(publicKey, curve.getCurveParams());
		this.privateKey = privateKey;
	}

	@Override
	public String name() {
		return "ECDH-ES+A256KW";
	}

	@Override
	public byte[] decrypt(JsonObject combinedHeader, byte[] encryptedKey) throws JoseDecryptException {
		if (privateKey == null) {
			throw new IllegalStateException("No private key available for decryption.");
		}

		// import ephemeral public key:
		if (!combinedHeader.has("epk")) {
			throw new IllegalStateException("No ephemeral public key available for decryption.");
		}
		var epk = fromJwk(combinedHeader.get("epk").getAsJsonObject());

		// derive shared secret using ECDH-ES:
		var sharedSecret = ecdh(epk, privateKey);

		// derive wrapping key using KDF:
		final SecretKey wrappingKey;
		try {
			var wrappingKeyBytes = deriveKey(sharedSecret, combinedHeader);
			wrappingKey = new SecretKeySpec(wrappingKeyBytes, type.jcaKeyAlgName);
		} finally {
			Arrays.fill(sharedSecret, (byte) 0x00);
		}

		// wrap using AES key wrap:
		try {
			Cipher cipher = Cipher.getInstance(type.jcaKwAlgName);
			cipher.init(Cipher.UNWRAP_MODE, wrappingKey);
			var unwrapped = cipher.unwrap(encryptedKey, "AES", Cipher.SECRET_KEY); // TODO: cek type depends...
			return unwrapped.getEncoded();
		} catch (NoSuchAlgorithmException | NoSuchPaddingException e) {
			throw new UnsupportedOperationException("JVM does not support " + type.jcaKwAlgName, e);
		} catch (InvalidKeyException e) {
			throw new IllegalStateException("Unsuitable wrapping key", e);
		} finally {
			Destroyables.destroyQuietly(wrappingKey);
		}
	}

	@Override
	public EncryptionResult encrypt(JsonObject combinedHeader, byte[] cek) {
		if (publicKey == null) {
			throw new IllegalStateException("No public key available for encryption.");
		}

		// generate ephemeral key pair:
		var keyPair = curve.generateKeyPair();
		final ECPrivateKey ephPrivateKey;
		final ECPublicKey ephPublicKey;
		if (keyPair.getPrivate() instanceof ECPrivateKey priv
				&& keyPair.getPublic() instanceof ECPublicKey pub) {
			ephPrivateKey = priv;
			ephPublicKey = pub;
		} else {
			throw new AssertionError("Key generated by EC key generator not an EC key");
		}

		// derive shared secret using ECDH-ES:
		final byte[] sharedSecret;
		try {
			sharedSecret = ecdh(publicKey, ephPrivateKey);
		} finally {
			Destroyables.destroyQuietly(ephPrivateKey);
		}

		// derive wrapping key using KDF:
		final SecretKey wrappingKey;
		try {
			var wrappingKeyBytes = deriveKey(sharedSecret, combinedHeader);
			wrappingKey = new SecretKeySpec(wrappingKeyBytes, type.jcaKeyAlgName);
		} finally {
			Arrays.fill(sharedSecret, (byte) 0x00);
		}

		// wrap using AES key wrap:
		final byte[] encryptedKey;
		try {
			SecretKey toBeWrapped = new SecretKeySpec(cek, "AES"); // TODO: cek type depends...
			Cipher cipher = Cipher.getInstance(type.jcaKwAlgName);
			cipher.init(Cipher.WRAP_MODE, wrappingKey);
			encryptedKey = cipher.wrap(toBeWrapped);
		} catch (NoSuchAlgorithmException | NoSuchPaddingException e) {
			throw new UnsupportedOperationException("JVM does not support " + type.jcaKwAlgName, e);
		} catch (InvalidKeyException e) {
			throw new IllegalStateException("Unsuitable wrapping key", e);
		} catch (IllegalBlockSizeException e) {
			throw new IllegalStateException("CEK not multiple of block size", e);
		} finally {
			Destroyables.destroyQuietly(wrappingKey);
		}

		// assemble header
		JsonObject perRecipientHeader = new JsonObject();
		perRecipientHeader.addProperty("alg", type.jwaAlgName);
		perRecipientHeader.add("epk", toJwk(ephPublicKey));
//		perRecipientHeader.addProperty("apu", combinedHeader.get("apu").getAsString());
//		perRecipientHeader.addProperty("apv", combinedHeader.get("apv").getAsString());
		return new EncryptionResult(encryptedKey, perRecipientHeader);
	}

	private byte[] ecdh(ECPublicKey publicKey, ECPrivateKey privateKey) {
		try {
			var keyAgreement = KeyAgreement.getInstance("ECDH");
			keyAgreement.init(privateKey);
			keyAgreement.doPhase(publicKey, true);
			return keyAgreement.generateSecret();
		} catch (NoSuchAlgorithmException e) {
			throw new UnsupportedOperationException("JVM does not support ECDH", e);
		} catch (InvalidKeyException e) {
			throw new IllegalStateException("Unsuitable key", e);
		}
	}

	private JsonObject toJwk(ECPublicKey publicKey) {
		JsonObject jwk = new JsonObject();
		jwk.addProperty("kty", EC_ALG);
		jwk.addProperty("crv", curve.jwaCrvName);
		jwk.addProperty("x", Base64.getUrlEncoder().withoutPadding().encodeToString(publicKey.getW().getAffineX().toByteArray()));
		jwk.addProperty("y", Base64.getUrlEncoder().withoutPadding().encodeToString(publicKey.getW().getAffineY().toByteArray()));
		return jwk;
	}

	private ECPublicKey fromJwk(JsonObject epk) throws DecryptKeyException {
		if (!epk.has("kty") || !epk.get("kty").getAsString().equals(EC_ALG)) {
			throw new DecryptKeyException("Not an EC key");
		}
		if (!epk.has("crv") || !epk.get("crv").getAsString().equals(curve.jwaCrvName)) {
			throw new DecryptKeyException("Key not for curve " + curve.jwaCrvName);
		}
		try {
			var keyFactory = KeyFactory.getInstance(EC_ALG);
			var point = new ECPoint(
					new BigInteger(1, Base64.getUrlDecoder().decode(epk.get("x").getAsString())),
					new BigInteger(1, Base64.getUrlDecoder().decode(epk.get("y").getAsString()))
			);
			var keySpec = new ECPublicKeySpec(point, curve.getCurveParams());
			if (keyFactory.generatePublic(keySpec) instanceof ECPublicKey k) {
				return ECHelper.validateKey(k, curve.getCurveParams());
			} else {
				throw new AssertionError("Key imported by EC key factory not an EC key");
			}
		} catch (NoSuchAlgorithmException e) {
			throw new UnsupportedOperationException("JVM does not support elliptic curves", e);
		} catch (InvalidKeySpecException e) {
			throw new DecryptKeyException("Unsuitable key spec", e);
		}
	}

	private byte[] deriveKey(byte[] sharedSecret, JsonObject combinedHeader) {
		var algorithmId = type.jwaAlgName.getBytes(StandardCharsets.US_ASCII); // TODO: if alg is "ECDH-ES" (without key wrap), use "enc" value from header
		var partyUInfo = combinedHeader.has("apu") ? Base64.getUrlDecoder().decode(combinedHeader.get("apu").getAsString()) : new byte[0];
		var partyVInfo = combinedHeader.has("apv") ? Base64.getUrlDecoder().decode(combinedHeader.get("apu").getAsString()) : new byte[0];
		var suppPubInfo = type.keyLength;
		var suppPrivInfo = new byte[0];
		ByteBuffer otherInfo = ByteBuffer.allocate(Integer.BYTES + algorithmId.length
				+ Integer.BYTES + partyUInfo.length
				+ Integer.BYTES + partyVInfo.length
				+ Integer.BYTES
				+ suppPrivInfo.length
		);
		otherInfo.putInt(algorithmId.length).put(algorithmId);
		otherInfo.putInt(partyUInfo.length).put(partyUInfo);
		otherInfo.putInt(partyVInfo.length).put(partyVInfo);
		otherInfo.putInt(suppPubInfo);
		otherInfo.put(suppPrivInfo);
		return ConcatKDF.sha256().kdf(sharedSecret, type.keyLength, otherInfo.array());
	}

}
